### ISSUE TITLE
Request: Tooltip for long function names

### ISSUE THREAD

**Issue by Red3Tango** [Maran23/script-ide#15]
Would be nice to have a tooltip on the function names if they are cut-off due to length.
Bottom image is default Godot.
![tooltip](https://github.com/Maran23/script-ide/assets/13739585/088c8fa7-931a-4baa-9ffd-106a5211c613)

**Comment by Maran23** [comment]
I actually disabled the tooltips as they consume all key events when activated. 
So when you open the outline popup and a tooltip appears when hovering over any item, you can not press an key.
Not sure if this can be fixed, maybe worth searching in the godot issues.

**Comment by Maran23** [comment]
Tooltips are now only deactivated in the Popup due to the bug I encountered above. 
They work as you expect in the Outline. :)

Enabled in Outline:
![image](https://github.com/Maran23/script-ide/assets/66004280/1de36927-8b4b-4c92-9ae1-f66c291238d8)

Disabled when Outline in Popup:
![image](https://github.com/Maran23/script-ide/assets/66004280/872ccf5e-2aa5-4604-a79e-5d4a486bec62)
