### ISSUE TITLE
Feature Request: Enhanced Code Navigation and Contextual Awareness for the Godot Script Editor

### ISSUE THREAD

**Issue by EiTaNBaRiBoA** [Maran23/script-ide#48]
* "Recently Used Scripts" Tab: Provide a dedicated tab for easy access to recently opened scripts, making it seamless to jump between actively worked-on files.
* "Current Script Context" List: Display a list of scripts directly related to the current file/script (e.g., those implementing it or being implementing by it), enabling easy navigation within the project's structure.
* Reference Counts: Display the number of references to a symbol directly above its function/class_name and providing immediate insight into its usage within the project.
* Reference Navigation Window: Upon clicking the reference count, open a window listing all reference locations, including the script name and line number, and allow navigation to those locations with a single click.

**Comment by Maran23** [comment]
Thanks for your request.
Your first point is somewhat implemented already with the three dots at the top right of the tabs:
![image](https://github.com/user-attachments/assets/c92f752f-7d01-413c-9d36-d86d4021fc14)

The other points you mentioned are out of scope for a plugin like this. 
Especially stuff like reference counts should be implemented at a much lower level, at the GD compiler tracking reference for us (so that we can use that information). If implemented by us, we can only count by the 'String' name, which is prone to errors as we have no contextual information.

I will therefore close this as not planned.

(Note that the idea is to get this plugin hopefully into Godot at one point, as any modern IDE has feature like that. Reference counting is a subject of its own, something with much value that would be nice to have in Godot core too)
